// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gmarcha/notion-trigger/internal/v1/goswagger/models"
)

// PoolCreateReader is a Reader for the PoolCreate structure.
type PoolCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PoolCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPoolCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPoolCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPoolCreateCreated creates a PoolCreateCreated with default headers values
func NewPoolCreateCreated() *PoolCreateCreated {
	return &PoolCreateCreated{}
}

/*
PoolCreateCreated describes a response with status code 201, with default header values.

Created
*/
type PoolCreateCreated struct {
	Payload []*models.Task
}

func (o *PoolCreateCreated) Error() string {
	return fmt.Sprintf("[POST /tasks/pools/{id}][%d] poolCreateCreated  %+v", 201, o.Payload)
}
func (o *PoolCreateCreated) GetPayload() []*models.Task {
	return o.Payload
}

func (o *PoolCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPoolCreateInternalServerError creates a PoolCreateInternalServerError with default headers values
func NewPoolCreateInternalServerError() *PoolCreateInternalServerError {
	return &PoolCreateInternalServerError{}
}

/*
PoolCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PoolCreateInternalServerError struct {
	Payload *models.Error
}

func (o *PoolCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /tasks/pools/{id}][%d] poolCreateInternalServerError  %+v", 500, o.Payload)
}
func (o *PoolCreateInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PoolCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
