// Code generated by go-swagger; DO NOT EDIT.

package campus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gmarcha/notion-trigger/internal/v1/goswagger/models"
)

// CreateTasksReader is a Reader for the CreateTasks structure.
type CreateTasksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTasksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateTasksCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCreateTasksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateTasksCreated creates a CreateTasksCreated with default headers values
func NewCreateTasksCreated() *CreateTasksCreated {
	return &CreateTasksCreated{}
}

/*
CreateTasksCreated describes a response with status code 201, with default header values.

Created
*/
type CreateTasksCreated struct {
	Payload []*models.Task
}

func (o *CreateTasksCreated) Error() string {
	return fmt.Sprintf("[POST /campus/{id}/tasks][%d] createTasksCreated  %+v", 201, o.Payload)
}
func (o *CreateTasksCreated) GetPayload() []*models.Task {
	return o.Payload
}

func (o *CreateTasksCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTasksInternalServerError creates a CreateTasksInternalServerError with default headers values
func NewCreateTasksInternalServerError() *CreateTasksInternalServerError {
	return &CreateTasksInternalServerError{}
}

/*
CreateTasksInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateTasksInternalServerError struct {
	Payload *models.Error
}

func (o *CreateTasksInternalServerError) Error() string {
	return fmt.Sprintf("[POST /campus/{id}/tasks][%d] createTasksInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateTasksInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateTasksInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
