// Code generated by go-swagger; DO NOT EDIT.

package campus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateTasksParams creates a new CreateTasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateTasksParams() *CreateTasksParams {
	return &CreateTasksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTasksParamsWithTimeout creates a new CreateTasksParams object
// with the ability to set a timeout on a request.
func NewCreateTasksParamsWithTimeout(timeout time.Duration) *CreateTasksParams {
	return &CreateTasksParams{
		timeout: timeout,
	}
}

// NewCreateTasksParamsWithContext creates a new CreateTasksParams object
// with the ability to set a context for a request.
func NewCreateTasksParamsWithContext(ctx context.Context) *CreateTasksParams {
	return &CreateTasksParams{
		Context: ctx,
	}
}

// NewCreateTasksParamsWithHTTPClient creates a new CreateTasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateTasksParamsWithHTTPClient(client *http.Client) *CreateTasksParams {
	return &CreateTasksParams{
		HTTPClient: client,
	}
}

/*
CreateTasksParams contains all the parameters to send to the API endpoint

	for the create tasks operation.

	Typically these are written to a http.Request.
*/
type CreateTasksParams struct {

	/* ID.

	   Campus ID.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTasksParams) WithDefaults() *CreateTasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create tasks params
func (o *CreateTasksParams) WithTimeout(timeout time.Duration) *CreateTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create tasks params
func (o *CreateTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create tasks params
func (o *CreateTasksParams) WithContext(ctx context.Context) *CreateTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create tasks params
func (o *CreateTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create tasks params
func (o *CreateTasksParams) WithHTTPClient(client *http.Client) *CreateTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create tasks params
func (o *CreateTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create tasks params
func (o *CreateTasksParams) WithID(id string) *CreateTasksParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create tasks params
func (o *CreateTasksParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
