// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gmarcha/notion-trigger/internal/v1/goswagger/models"
)

// CampusCreateReader is a Reader for the CampusCreate structure.
type CampusCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CampusCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCampusCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCampusCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCampusCreateCreated creates a CampusCreateCreated with default headers values
func NewCampusCreateCreated() *CampusCreateCreated {
	return &CampusCreateCreated{}
}

/*
CampusCreateCreated describes a response with status code 201, with default header values.

Created
*/
type CampusCreateCreated struct {
	Payload []*models.Task
}

func (o *CampusCreateCreated) Error() string {
	return fmt.Sprintf("[POST /tasks/campuses/{id}][%d] campusCreateCreated  %+v", 201, o.Payload)
}
func (o *CampusCreateCreated) GetPayload() []*models.Task {
	return o.Payload
}

func (o *CampusCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCampusCreateInternalServerError creates a CampusCreateInternalServerError with default headers values
func NewCampusCreateInternalServerError() *CampusCreateInternalServerError {
	return &CampusCreateInternalServerError{}
}

/*
CampusCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CampusCreateInternalServerError struct {
	Payload *models.Error
}

func (o *CampusCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /tasks/campuses/{id}][%d] campusCreateInternalServerError  %+v", 500, o.Payload)
}
func (o *CampusCreateInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CampusCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
